@host = http://localhost:8080
@id = 

### Create user
POST {{host}}/api/users
Content-Type: application/json

{
    "name": "John",
    "email": "john@email.com",
    "username": "john_username",
    "password": "john_password"
}

### Get single user
GET {{host}}/api/users/{{id}}
Content-Type: application/json

### Update existing user
PUT {{host}}/api/users/{{id}}
Content-Type: application/json

{
    "name": "John Update",
    "email": "john@email.com",
    "username": "john_username1",
    "password": "john_password1"
}

### Delete single user
DELETE {{host}}/api/users/{{id}}
Content-Type: application/json
