@host = http://localhost:8080
@token = 

### Create
POST {{host}}/api/users
Content-Type: application/json

{
    "name": "John",
    "email": "john@email.com",
    "username": "john_username",
    "password": "john_password"
}

### Get token
POST {{host}}/api/users/token
Content-Type: application/json

{
    "username": "john_username",
    "password": "john_password"
}

### Read
GET {{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

### Update
PUT {{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "John Update",
    "email": "john@email.com",
    "username": "john_username1",
    "password": "john_password1"
}

### Delete
DELETE {{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}
