version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/rvapi"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/rvapi"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
