@token = 
@tagId = 

### Create tag, single
POST http://localhost:8080/tags/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tagname": "single1",
  "reponame": "single1/single1"
}

### Create tag, batch
POST http://localhost:8080/tags/create/batch
Content-Type: application/json
Authorization: Bearer {{token}}

[
  {
    "tagname": "batch1",
    "reponame": "batch1/batch1"
  },
  {
    "tagname": "batch2",
    "reponame": "batch2/batch2"
  },
  {
    "tagname": "batch3",
    "reponame": "batch3/batch3"
  }
]

### Toggle tag hide
PUT http://localhost:8080/tags/{{tagId}}/toggle-hide
Content-Type: application/json
Authorization: Bearer {{token}}

### Toggle tag show
PUT http://localhost:8080/tags/{{tagId}}/toggle-show
Content-Type: application/json
Authorization: Bearer {{token}}

### Show all user tags
GET http://localhost:8080/tags/all
Content-Type: application/json
Authorization: Bearer {{token}}

### Update single tag
PUT http://localhost:8080/tags/update/{{tagId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tagname": "arch",
  "reponame": "arch/btw"
}
