name: Run tests

on:
  workflow_dispatch:
  push:
    paths:
      - rvapi/src/main/java/com/korg/rvapi/auth/**
      - rvapi/src/test/java/com/korg/rvapi/**

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run Maven tests
        run: cd rvapi && mvn -B test --file pom.xml
